# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='title_short',
            field=models.CharField(default='nome padrão', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='market',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
