# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20160601_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='market_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.MarketCategory'),
        ),
    ]
