# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20160628_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed',
            field=models.BooleanField(default=0),
        ),
    ]
