# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20160601_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='from_order_id',
            new_name='from_order',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='to_order_id',
            new_name='to_order',
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together=set([('from_order', 'to_order')]),
        ),
    ]
