# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_event_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='closed',
            new_name='liquidated',
        ),
    ]
