# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 02:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20160601_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
