# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_market_winning_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='winning_choice',
        ),
    ]
