# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_operation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='residual',
            field=models.BooleanField(default=0),
        ),
    ]
