# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_market_winning_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='winner',
            field=models.BooleanField(default=0),
        ),
    ]
