# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_order_residual'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(default=0),
        ),
    ]
