# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_choice_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='liquidated',
        ),
        migrations.AddField(
            model_name='market',
            name='liquidated',
            field=models.BooleanField(default=0),
        ),
    ]
