# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_eventcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='from_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_order', to='market.Order'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='to_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_order', to='market.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Choice'),
        ),
    ]
