# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20160717_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='market',
        ),
        migrations.RemoveField(
            model_name='order',
            name='choice',
        ),
        migrations.AddField(
            model_name='market',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='market',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='market.Market'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
