# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20160725_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
