# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20161222_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
