# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20160609_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
